//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtakuAssetManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_Asset
    {
        public long AssetID { get; set; }
        public long AssetNo { get; set; }
        public string AssetName { get; set; }
        public int UseCategory { get; set; }
        public short Amount { get; set; }
        public byte Status { get; set; }
        public int GetDate { get; set; }
        public byte GetReason { get; set; }
        public int TransferDate { get; set; }
        public byte TransferReason { get; set; }
        public int BelongingID { get; set; }
        public int PlaceID { get; set; }
        public int InsertDate { get; set; }
        public int UpdateDate { get; set; }
    }
}
